apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pia-data
  namespace: pia
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pia-logs
  namespace: pia
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
